Config file config/config.yaml is extended by additional config specified via the command line.
Building DAG of jobs...
Provided cores: 8
Rules claiming more threads will be scaled down.
Conda environments: ignored
Job stats:
job              count
-------------  -------
solve_network        1
total                1

Select jobs to execute...

[Tue Apr  2 13:44:58 2024]
rule solve_network:
    input: resources/live_data/2024-03-25_12/network_s_nodal.nc
    output: resources/live_data/2024-03-25_12/network_s_nodal_solved.nc
    log: logs/pypsa-lmp/solve_network_2024-03-25_12_s_nodal.log
    jobid: 9
    reason: Missing output files: resources/live_data/2024-03-25_12/network_s_nodal_solved.nc
    wildcards: date=2024-03-25, period=12, layout=nodal
    resources: tmpdir=C:\Users\alyden\AppData\Local\Temp, mem_mb=1500, mem_mib=1431

[Tue Apr  2 13:45:05 2024]
Error in rule solve_network:
    jobid: 9
    input: resources/live_data/2024-03-25_12/network_s_nodal.nc
    output: resources/live_data/2024-03-25_12/network_s_nodal_solved.nc
    log: logs/pypsa-lmp/solve_network_2024-03-25_12_s_nodal.log (check log file(s) for error details)
    conda-env: C:\Users\alyden\OneDrive - University of Edinburgh\Python\LMP\.snakemake\conda\cf0dbe1799d06fa5b5ff98f73b111298_

RuleException:
CalledProcessError in file C:\Users\alyden\OneDrive - University of Edinburgh\Python\LMP\Snakefile, line 377:
Command 'C:/Users/alyden/AppData/Local/miniforge3/envs/pypsa-lmp/python.exe "C:\Users\alyden\OneDrive - University of Edinburgh\Python\LMP\.snakemake\scripts\tmpayhgncob.solve_network.py"' returned non-zero exit status 1.
  File "C:\Users\alyden\OneDrive - University of Edinburgh\Python\LMP\Snakefile", line 377, in __rule_solve_network
  File "C:\Users\alyden\AppData\Local\miniforge3\envs\pypsa-lmp\Lib\concurrent\futures\thread.py", line 58, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake\log\2024-04-02T134457.533377.snakemake.log
