Config file config/config.yaml is extended by additional config specified via the command line.
Building DAG of jobs...
Provided cores: 8
Rules claiming more threads will be scaled down.
Conda environments: ignored
Job stats:
job                     count
--------------------  -------
add_generators              1
cluster_network             1
prepare_live_network        1
simplify_network            1
solve_network               1
total                       5

Select jobs to execute...

[Fri Mar 29 14:12:02 2024]
rule add_generators:
    input: data/ETYS_base.nc, data/gb_shape.geojson, resources/bmunits_loc.csv, resources/regions_onshore.geojson, resources/regions_offshore.geojson, data/manual/carrier_costs.yaml
    output: resources/networks/gen.nc
    log: logs/pypsa-lmp/add_generators.log
    jobid: 2
    reason: Missing output files: resources/networks/gen.nc; Updated input files: data/ETYS_base.nc, resources/regions_offshore.geojson, resources/regions_onshore.geojson
    resources: tmpdir=C:\Users\alyden\AppData\Local\Temp, mem_mb=1000, mem_mib=954

[Fri Mar 29 14:12:18 2024]
Error in rule add_generators:
    jobid: 2
    input: data/ETYS_base.nc, data/gb_shape.geojson, resources/bmunits_loc.csv, resources/regions_onshore.geojson, resources/regions_offshore.geojson, data/manual/carrier_costs.yaml
    output: resources/networks/gen.nc
    log: logs/pypsa-lmp/add_generators.log (check log file(s) for error details)
    conda-env: C:\Users\alyden\OneDrive - University of Edinburgh\Python\LMP\.snakemake\conda\cf0dbe1799d06fa5b5ff98f73b111298_

RuleException:
CalledProcessError in file C:\Users\alyden\OneDrive - University of Edinburgh\Python\LMP\Snakefile, line 236:
Command 'C:/Users/alyden/AppData/Local/miniforge3/envs/pypsa-lmp/python.exe "C:\Users\alyden\OneDrive - University of Edinburgh\Python\LMP\.snakemake\scripts\tmpgtwj8vuo.add_generators.py"' returned non-zero exit status 1.
  File "C:\Users\alyden\OneDrive - University of Edinburgh\Python\LMP\Snakefile", line 236, in __rule_add_generators
  File "C:\Users\alyden\AppData\Local\miniforge3\envs\pypsa-lmp\Lib\concurrent\futures\thread.py", line 58, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake\log\2024-03-29T141202.208762.snakemake.log
